export interface BibleBook {
  name: string;        // Portuguese name
  slug: string;        // English slug for bible-api
  chapters: number;
  testament: "AT" | "NT";
}

export const BIBLE_BOOKS: BibleBook[] = [
  // Antigo Testamento
  { name: "Gênesis", slug: "genesis", chapters: 50, testament: "AT" },
  { name: "Êxodo", slug: "exodus", chapters: 40, testament: "AT" },
  { name: "Levítico", slug: "leviticus", chapters: 27, testament: "AT" },
  { name: "Números", slug: "numbers", chapters: 36, testament: "AT" },
  { name: "Deuteronômio", slug: "deuteronomy", chapters: 34, testament: "AT" },
  { name: "Josué", slug: "joshua", chapters: 24, testament: "AT" },
  { name: "Juízes", slug: "judges", chapters: 21, testament: "AT" },
  { name: "Rute", slug: "ruth", chapters: 4, testament: "AT" },
  { name: "1 Samuel", slug: "1 samuel", chapters: 31, testament: "AT" },
  { name: "2 Samuel", slug: "2 samuel", chapters: 24, testament: "AT" },
  { name: "1 Reis", slug: "1 kings", chapters: 22, testament: "AT" },
  { name: "2 Reis", slug: "2 kings", chapters: 25, testament: "AT" },
  { name: "1 Crônicas", slug: "1 chronicles", chapters: 29, testament: "AT" },
  { name: "2 Crônicas", slug: "2 chronicles", chapters: 36, testament: "AT" },
  { name: "Esdras", slug: "ezra", chapters: 10, testament: "AT" },
  { name: "Neemias", slug: "nehemiah", chapters: 13, testament: "AT" },
  { name: "Ester", slug: "esther", chapters: 10, testament: "AT" },
  { name: "Jó", slug: "job", chapters: 42, testament: "AT" },
  { name: "Salmos", slug: "psalms", chapters: 150, testament: "AT" },
  { name: "Provérbios", slug: "proverbs", chapters: 31, testament: "AT" },
  { name: "Eclesiastes", slug: "ecclesiastes", chapters: 12, testament: "AT" },
  { name: "Cânticos", slug: "song of solomon", chapters: 8, testament: "AT" },
  { name: "Isaías", slug: "isaiah", chapters: 66, testament: "AT" },
  { name: "Jeremias", slug: "jeremiah", chapters: 52, testament: "AT" },
  { name: "Lamentações", slug: "lamentations", chapters: 5, testament: "AT" },
  { name: "Ezequiel", slug: "ezekiel", chapters: 48, testament: "AT" },
  { name: "Daniel", slug: "daniel", chapters: 12, testament: "AT" },
  { name: "Oséias", slug: "hosea", chapters: 14, testament: "AT" },
  { name: "Joel", slug: "joel", chapters: 3, testament: "AT" },
  { name: "Amós", slug: "amos", chapters: 9, testament: "AT" },
  { name: "Obadias", slug: "obadiah", chapters: 1, testament: "AT" },
  { name: "Jonas", slug: "jonah", chapters: 4, testament: "AT" },
  { name: "Miquéias", slug: "micah", chapters: 7, testament: "AT" },
  { name: "Naum", slug: "nahum", chapters: 3, testament: "AT" },
  { name: "Habacuque", slug: "habakkuk", chapters: 3, testament: "AT" },
  { name: "Sofonias", slug: "zephaniah", chapters: 3, testament: "AT" },
  { name: "Ageu", slug: "haggai", chapters: 2, testament: "AT" },
  { name: "Zacarias", slug: "zechariah", chapters: 14, testament: "AT" },
  { name: "Malaquias", slug: "malachi", chapters: 4, testament: "AT" },
  // Novo Testamento
  { name: "Mateus", slug: "matthew", chapters: 28, testament: "NT" },
  { name: "Marcos", slug: "mark", chapters: 16, testament: "NT" },
  { name: "Lucas", slug: "luke", chapters: 24, testament: "NT" },
  { name: "João", slug: "john", chapters: 21, testament: "NT" },
  { name: "Atos", slug: "acts", chapters: 28, testament: "NT" },
  { name: "Romanos", slug: "romans", chapters: 16, testament: "NT" },
  { name: "1 Coríntios", slug: "1 corinthians", chapters: 16, testament: "NT" },
  { name: "2 Coríntios", slug: "2 corinthians", chapters: 13, testament: "NT" },
  { name: "Gálatas", slug: "galatians", chapters: 6, testament: "NT" },
  { name: "Efésios", slug: "ephesians", chapters: 6, testament: "NT" },
  { name: "Filipenses", slug: "philippians", chapters: 4, testament: "NT" },
  { name: "Colossenses", slug: "colossians", chapters: 4, testament: "NT" },
  { name: "1 Tessalonicenses", slug: "1 thessalonians", chapters: 5, testament: "NT" },
  { name: "2 Tessalonicenses", slug: "2 thessalonians", chapters: 3, testament: "NT" },
  { name: "1 Timóteo", slug: "1 timothy", chapters: 6, testament: "NT" },
  { name: "2 Timóteo", slug: "2 timothy", chapters: 4, testament: "NT" },
  { name: "Tito", slug: "titus", chapters: 3, testament: "NT" },
  { name: "Filemom", slug: "philemon", chapters: 1, testament: "NT" },
  { name: "Hebreus", slug: "hebrews", chapters: 13, testament: "NT" },
  { name: "Tiago", slug: "james", chapters: 5, testament: "NT" },
  { name: "1 Pedro", slug: "1 peter", chapters: 5, testament: "NT" },
  { name: "2 Pedro", slug: "2 peter", chapters: 3, testament: "NT" },
  { name: "1 João", slug: "1 john", chapters: 5, testament: "NT" },
  { name: "2 João", slug: "2 john", chapters: 1, testament: "NT" },
  { name: "3 João", slug: "3 john", chapters: 1, testament: "NT" },
  { name: "Judas", slug: "jude", chapters: 1, testament: "NT" },
  { name: "Apocalipse", slug: "revelation", chapters: 22, testament: "NT" },
];

export const getBookBySlug = (slug: string) =>
  BIBLE_BOOKS.find((b) => b.slug === slug);
