// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-writer-documents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_writer_documents_default = defineTool({
  name: "list_writer_documents",
  title: "List Writer documents",
  description: "List the signed-in user's Writer documents (sermons, devotionals, notes) in RC Bible, most recently updated first.",
  inputSchema: {
    type: z.enum(["sermon", "devotional", "note"]).optional().describe("Optional document type filter."),
    include_archived: z.boolean().optional().describe("Include archived documents (default false)."),
    limit: z.number().int().optional().describe("Maximum number of documents to return (1-50, default 20).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ type, include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const cappedLimit = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("user_documents").select("id, type, title, tags, is_archived, created_at, updated_at").order("updated_at", { ascending: false }).limit(cappedLimit);
    if (type) query = query.eq("type", type);
    if (!include_archived) query = query.eq("is_archived", false);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-writer-document.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_writer_document_default = defineTool2({
  name: "get_writer_document",
  title: "Get Writer document",
  description: "Read the full markdown content of one of the signed-in user's Writer documents in RC Bible.",
  inputSchema: {
    document_id: z2.string().uuid().describe("UUID of the document to fetch. Get IDs via list_writer_documents.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ document_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("user_documents").select(
      "id, type, title, content_md, tags, is_archived, created_at, updated_at"
    ).eq("id", document_id).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "Document not found." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { document: data }
    };
  }
});

// src/lib/mcp/tools/create-writer-note.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_writer_note_default = defineTool3({
  name: "create_writer_note",
  title: "Create Writer note",
  description: "Create a new document (sermon, devotional, or note) in the signed-in user's Writer library in RC Bible.",
  inputSchema: {
    type: z3.enum(["sermon", "devotional", "note"]).describe("Document category."),
    title: z3.string().trim().min(1).describe("Document title."),
    content_md: z3.string().describe("Markdown body. Bible references like 'Jo\xE3o 3:16' are auto-detected on save."),
    tags: z3.array(z3.string().trim().min(1)).optional().describe("Optional tag list.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async ({ type, title, content_md, tags }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("user_documents").insert({
      user_id: ctx.getUserId(),
      type,
      title,
      content_md,
      tags: tags ?? []
    }).select("id, type, title, created_at, updated_at").single();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        { type: "text", text: `Created ${type} "${title}" (${data.id}).` }
      ],
      structuredContent: { document: data }
    };
  }
});

// src/lib/mcp/tools/list-verse-highlights.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_verse_highlights_default = defineTool4({
  name: "list_verse_highlights",
  title: "List verse highlights",
  description: "List the signed-in user's most recent verse highlights (with optional notes and color) in RC Bible.",
  inputSchema: {
    book_slug: z4.string().trim().min(1).optional().describe("Optional book slug filter (e.g. 'joao', 'romanos')."),
    chapter: z4.number().int().min(1).optional().describe("Optional chapter filter (requires book_slug)."),
    limit: z4.number().int().optional().describe("Maximum highlights to return (1-100, default 30).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ book_slug, chapter, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const cappedLimit = Math.min(Math.max(limit ?? 30, 1), 100);
    const supabase = supabaseForUser4(ctx);
    let query = supabase.from("verse_highlights").select("*").order("created_at", { ascending: false }).limit(cappedLimit);
    if (book_slug) query = query.eq("book_slug", book_slug);
    if (chapter) query = query.eq("chapter", chapter);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { highlights: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-writer.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_writer_default = defineTool5({
  name: "search_writer",
  title: "Search Writer",
  description: "Search the signed-in user's Writer documents by free text, tag, and/or bible reference (book_slug + optional chapter/verse).",
  inputSchema: {
    query: z5.string().trim().optional().describe("Free-text search across title, content, and tags."),
    tag: z5.string().trim().optional().describe("Exact tag filter."),
    book_slug: z5.string().trim().optional().describe("Bible reference book slug filter (e.g. 'joao')."),
    chapter: z5.number().int().min(1).optional(),
    verse: z5.number().int().min(1).optional(),
    include_archived: z5.boolean().optional(),
    limit: z5.number().int().optional().describe("Max results (1-50, default 20).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.rpc("search_user_documents", {
      p_query: input.query ?? null,
      p_archived: input.include_archived ?? false,
      p_tag: input.tag ?? null,
      p_book_slug: input.book_slug ?? null,
      p_chapter: input.chapter ?? null,
      p_verse: input.verse ?? null,
      p_limit: Math.min(Math.max(input.limit ?? 20, 1), 50),
      p_offset: 0
    });
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vhesthnnsvrfvfmpuwvf";
var mcp_default = defineMcp({
  name: "rc-bible-mcp",
  title: "RC Bible",
  version: "0.1.0",
  instructions: "Access the signed-in user's RC Bible study workspace. Use `list_writer_documents` and `get_writer_document` to read their sermons, devotionals, and notes; `create_writer_note` to add a new document; `list_verse_highlights` to see highlighted verses; and `search_writer` to search across their library by text, tag, or bible reference (book/chapter/verse).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_writer_documents_default,
    get_writer_document_default,
    create_writer_note_default,
    list_verse_highlights_default,
    search_writer_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
